openapi: 3.0.1
info:
  title: Autonomous Vehicle SDM
  version: "1.0.0"
  description: SDM with Device, DeviceModel, AutonomousVehicle and Measurements.

paths: {}

components:
  schemas:

    AutonomousVehicle:
      $ref: "https://raw.githubusercontent.com/hugorevu/dataModel.AutonomousVehicle/refs/heads/fiware-device/FIWARE_DEVICE_MODEL/AutonomousVehicle.yaml"

    Device:
      $ref: "https://raw.githubusercontent.com/hugorevu/dataModel.AutonomousVehicle/refs/heads/fiware-device/FIWARE_DEVICE_MODEL/Device.yaml"

    DeviceModel:
      $ref: "https://raw.githubusercontent.com/hugorevu/dataModel.AutonomousVehicle/refs/heads/fiware-device/FIWARE_DEVICE_MODEL/DeviceModel.yaml"

    DeviceMeasurement:
      $ref: "https://raw.githubusercontent.com/hugorevu/dataModel.AutonomousVehicle/refs/heads/fiware-device/FIWARE_DEVICE_MODEL/DeviceMeasurement.yaml"