@echo off

echo Deleting AutonomousVehicle...
curl -X DELETE http://localhost:8080/ngsi-ld/v1/entities/urn:ngsi-ld:AutonomousVehicle:001
echo Deleting DeviceModel...
curl -X DELETE http://localhost:8080/ngsi-ld/v1/entities/urn:ngsi-ld:DeviceModel:CameraModelX
echo Deleting Device...
curl -X DELETE http://localhost:8080/ngsi-ld/v1/entities/urn:ngsi-ld:Device:Camera001
echo Deleting Measurement...
curl -X DELETE http://localhost:8080/ngsi-ld/v1/entities/urn:ngsi-ld:DeviceMeasurement:001
echo Deleting Device for GNSS...
curl -X DELETE http://localhost:8080/ngsi-ld/v1/entities/urn:ngsi-ld:Device:GNSS001
echo Deleting DeviceModel for GNSS...
curl -X DELETE http://localhost:8080/ngsi-ld/v1/entities/urn:ngsi-ld:DeviceModel:GNSSModelX
echo Deleting Measurement for GNSS...
curl -X DELETE http://localhost:8080/ngsi-ld/v1/entities/urn:ngsi-ld:DeviceMeasurement:GNSS001
echo Done.
pause